[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = ["arch/x86_64-unknown-none.json"]

[target.'arch/x86_64-unknown-none.json']
rustflags = [
    "-C", "code-model=kernel",
    "-C", "link-arg=-Tlink.ld",
    "-C", "relocation-model=static",
]