[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = ["arch/x86_64-unknown-none.json"]

[target.'arch/x86_64-unknown-none.json']
linker = "ld.lld"
rustflags = ["-C", "link-arg=-Tsrc/link.ld", "-C", "relocation-model=static"]